# Generated by Django 4.0.1 on 2022-01-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('age', models.IntegerField(max_length=2)),
                ('password', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
    ]
