# Generated by Django 4.0.1 on 2022-01-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_author_email_alter_author_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
