version: '3.3'

services:
  web:
    # Берем Dockerfile из каталога firstapp
    build: ./firstapp
    # Запускаем тестовый сервер
    command: python manage.py runserver 0.0.0.0:8081
    # куда будут помещены данные из каталога app
    volumes:
      - ./app/:/root/project/firstapp/
    # Открываем порт 8081
    ports:
      - 8081:8081
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env.dev

